parameters:
- name: 'EnableIIS'
  type: string
- name: 'IISDeploymentType'
  type: string
- name: 'ActionIISWebsite'
  type: string	
- name: 'WebsiteName'
  type: string
# - name: 'WebsitePhysicalPath'
#   type: string
- name: 'WebsiteAuthUserName'
  type: string  
# - name: 'WebsiteAuthUserPassword'
#   type: string
- name: 'Package'
  type: string
- name: 'DotNetVersionForWebsite'
  type: string

steps:
- task: PowerShell@2
  inputs:
      targetType: 'inline'
      script: |                         
        Write-Host "System default working Directory -> $(System.DefaultWorkingDirectory)"
        Write-Host "Build Artifact Publish Path -> $(build.artifactStagingDirectory)"

- task: IISWebAppManagementOnMachineGroup@0
  inputs:
      EnableIIS: '${{ Parameters.EnableIIS }}'
      IISDeploymentType: '${{ Parameters.IISDeploymentType }}'
      ActionIISWebsite: '${{ Parameters.ActionIISWebsite }}'
      WebsiteName: '${{ Parameters.WebsiteName }}'
      WebsitePhysicalPath: '%SystemDrive%\appDeploy\${{Parameters.WebsiteName}}'
      WebsitePhysicalPathAuth: 'WebsiteWindowsAuth'
      WebsiteAuthUserName: '${{ Parameters.WebsiteAuthUserName }}'
      #WebsiteAuthUserPassword: '${{ Parameters.WebsiteAuthUserPassword }}'
      WebsiteAuthUserPassword: $(Password)
      CreateOrUpdateAppPoolForWebsite: true
      AppPoolNameForWebsite: '${{ Parameters.WebsiteName }}'
      DotNetVersionForWebsite: '${{ Parameters.DotNetVersionForWebsite }}'
      PipeLineModeForWebsite: 'Integrated'
      AppPoolIdentityForWebsite: 'ApplicationPoolIdentity'
      AddBinding: true
      Bindings: |
                  {
                      bindings:[
                          {
                              "protocol":"http",
                              "ipAddress":"",
                              "hostname":"$(hostname-qa)",
                              "port":"80",
                              "sslThumbprint":"",
                              "sniFlag":false
                          }
                      ]
                  }
   
- task: IISWebAppDeploymentOnMachineGroup@0
  inputs:
      WebSiteName: '${{ Parameters.WebsiteName }}'
      Package: '${{ Parameters.Package }}'